# Generated by Django 4.1.3 on 2023-01-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="money",
            field=models.DecimalField(decimal_places=7, max_digits=7, null=True),
        ),
    ]
