# Generated by Django 4.1.3 on 2023-01-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0003_auction_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="actual_price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name="user",
            name="money",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
