# Generated by Django 4.1.5 on 2023-01-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0004_alter_auction_actual_price_alter_user_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="actual_price",
            field=models.IntegerField(),
        ),
    ]
