# Generated by Django 4.1.5 on 2023-01-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0005_alter_auction_actual_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="actual_price",
            field=models.IntegerField(null=True),
        ),
    ]
