# Generated by Django 4.1.5 on 2023-01-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0006_alter_auction_actual_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="actual_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
