# Generated by Django 4.1.5 on 2023-01-12 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0008_alter_auction_owner_alter_auction_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="offered_the_most",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_offered_the_most",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
