# Generated by Django 4.1.3 on 2023-01-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0009_auction_offered_the_most"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="owner_to_chat_with",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="won_item_title",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
