# Generated by Django 4.1.3 on 2023-01-17 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0010_user_owner_to_chat_with_user_won_item_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="offered_the_most",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_offered_the_most",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_winner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
