# Generated by Django 4.1.3 on 2023-01-17 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0011_alter_auction_offered_the_most_alter_auction_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_winner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
